// 사이트 전역 설정 - 배포 전 실제 도메인으로 변경 필요
export const siteConfig = {
  // GitHub Pages 배포 시 사용할 기본 URL (예: https://username.github.io/tool-hub)
  siteUrl: 'https://asa9874.github.io/tool-hub',
  siteName: 'ToolHub - 무료 온라인 도구 모음',
  siteDescription: '만나이 계산기, 전역일 계산기, 글자수 세기, JSON 포맷터, 대출 이자 계산기, BMI 계산기 등 다양한 무료 온라인 도구를 제공합니다.',
  defaultLanguage: 'ko',
  
  // AdSense 설정 (승인 후 실제 값으로 변경)
  adsense: {
    clientId: 'ca-pub-XXXXXXXXXXXXXXXX', // 실제 AdSense 클라이언트 ID로 변경
    enabled: false, // 승인 후 true로 변경
  },
  
  // 소셜 미디어 (선택사항)
  social: {
    twitter: '',
    github: '',
  },

  // 도구 목록 - 새 도구 추가 시 여기에 등록
  tools: [
    // === 금융/부동산 분야 (광고 단가 높음) ===
    {
      id: 'loan-calculator',
      path: '/tools/loan-calculator',
      title: '대출 이자 계산기 - 원리금균등/원금균등 상환 계산 (2026년)',
      description: '주택담보대출, 전세자금대출 등 대출 원금과 금리를 입력하면 월 상환금, 총 이자를 계산합니다. 원리금균등, 원금균등, 만기일시 상환 방식 지원.',
      keywords: ['대출 이자 계산기', '원리금균등상환', '원금균등상환', '주택담보대출', '대출 이자', '월 상환금 계산'],
      category: '금융/부동산',
    },
    {
      id: 'savings-calculator',
      path: '/tools/savings-calculator',
      title: '예적금 이자 계산기 - 세전/세후 이자 계산 (비과세 포함)',
      description: '예금, 적금의 원금과 금리를 입력하면 세금을 제외한 실제 수령 이자와 만기 수령액을 계산합니다. 일반과세, 세금우대, 비과세 지원.',
      keywords: ['예적금 이자 계산기', '적금 이자', '예금 이자', '비과세 이자', '세후 이자', '만기 수령액'],
      category: '금융/부동산',
    },
    {
      id: 'brokerage-fee-calculator',
      path: '/tools/brokerage-fee-calculator',
      title: '부동산 중개수수료 계산기 - 복비 계산 (2024년 요율표)',
      description: '아파트, 오피스텔 매매/전세/월세 거래 시 부동산 중개수수료(복비)를 계산합니다. 2024년 최신 요율표 적용.',
      keywords: ['부동산 중개수수료', '복비 계산기', '중개보수', '매매 수수료', '전세 수수료', '부동산 복비'],
      category: '금융/부동산',
    },
    {
      id: 'severance-calculator',
      path: '/tools/severance-calculator',
      title: '퇴직금 계산기 - 근속연수별 퇴직금 계산 (세금 포함)',
      description: '입사일, 퇴사일, 월 평균임금을 입력하면 퇴직금과 퇴직소득세를 계산합니다. 퇴직금 지급 기준 확인.',
      keywords: ['퇴직금 계산기', '퇴직금 계산', '퇴직소득세', '근속연수', '평균임금', '퇴직금 세금'],
      category: '금융/부동산',
    },
    
    // === 건강/라이프스타일 분야 ===
    {
      id: 'bmi-calculator',
      path: '/tools/bmi-calculator',
      title: 'BMI 계산기 - 체질량지수 비만도 측정 (아시아 기준)',
      description: '키와 몸무게를 입력하면 BMI(체질량지수)와 비만도를 확인합니다. WHO 아시아-태평양 기준 적용.',
      keywords: ['BMI 계산기', '체질량지수', '비만도 계산', '비만 측정', '적정 체중', '다이어트'],
      category: '건강/라이프스타일',
    },
    {
      id: 'bmr-calculator',
      path: '/tools/bmr-calculator',
      title: '기초대사량(BMR) 계산기 - 하루 칼로리 소모량 계산',
      description: '나이, 성별, 키, 몸무게로 기초대사량(BMR)과 활동대사량(TDEE)을 계산합니다. 다이어트 칼로리 목표 설정.',
      keywords: ['기초대사량 계산기', 'BMR 계산', 'TDEE', '칼로리 소모량', '다이어트 칼로리', '하루 권장 칼로리'],
      category: '건강/라이프스타일',
    },
    {
      id: 'calorie-burn-calculator',
      path: '/tools/calorie-burn-calculator',
      title: '운동 칼로리 소모 계산기 - 활동별 소모 칼로리',
      description: '운동 종류와 시간을 입력하면 소모 칼로리를 계산합니다. 걷기, 달리기, 수영, 등산 등 50가지 이상 활동 지원.',
      keywords: ['운동 칼로리', '칼로리 소모', '운동 칼로리 계산기', '등산 칼로리', '달리기 칼로리', 'MET'],
      category: '건강/라이프스타일',
    },

    // === 생활/사회 분야 ===
    {
      id: 'age-calculator',
      path: '/tools/age-calculator',
      title: '2026년 만나이 계산기 - 정확한 나이 계산 (만나이 통일법 적용)',
      description: '생년월일을 입력하면 만나이, 한국식 나이, 연나이를 정확하게 계산해드립니다. 2023년 6월 만나이 통일법 적용.',
      keywords: ['만나이 계산기', '나이 계산', '한국 나이', '만나이 통일법', '생년월일 계산', '2026년 나이'],
      category: '생활/사회',
    },
    {
      id: 'military-calculator',
      path: '/tools/military-calculator',
      title: '전역일 계산기 - 육군/해군/공군 복무일수 계산 (2026년)',
      description: '입대일을 입력하면 전역일, 복무한 일수, 남은 일수를 정확하게 계산합니다. 육군, 해군, 공군, 사회복무요원 지원.',
      keywords: ['전역일 계산기', '군대 전역일', '복무일수 계산', '육군 전역일', '공군 전역일', '해군 전역일'],
      category: '생활/사회',
    },
    {
      id: 'gpa-calculator',
      path: '/tools/gpa-calculator',
      title: '대학교 학점 계산기 - 평균 평점(GPA) 계산 (4.5 만점)',
      description: '과목별 학점과 성적을 입력하면 평균 학점(GPA)을 자동으로 계산합니다. 4.5 만점 기준.',
      keywords: ['학점 계산기', 'GPA 계산', '평균 학점', '대학 학점', '성적 계산'],
      category: '생활/사회',
    },
    {
      id: 'salary-calculator',
      path: '/tools/salary-calculator',
      title: '2026년 실수령액 계산기 - 연봉 세후 월급 계산',
      description: '연봉 입력 시 4대 보험과 소득세를 제외한 실제 월급(실수령액)을 계산합니다. 2024년 세율 기준.',
      keywords: ['실수령액 계산기', '연봉 계산기', '월급 계산', '세후 월급', '4대 보험 계산'],
      category: '생활/사회',
    },
    {
      id: 'zodiac-calculator',
      path: '/tools/zodiac-calculator',
      title: '띠 & 별자리 계산기 - 12간지, 생일 별자리 확인',
      description: '생년월일로 띠(12간지)와 별자리를 확인하세요. 다음 생일까지 며칠 남았는지도 알려드립니다.',
      keywords: ['띠 계산기', '별자리 계산기', '12간지', '생일 별자리', '다음 생일'],
      category: '생활/사회',
    },
    {
      id: 'd-day-calculator',
      path: '/tools/d-day-calculator',
      title: 'D-Day 계산기 - 기념일, 시험일까지 남은 일수',
      description: '특정 날짜까지 남은 일수(D-Day)를 계산합니다. 기념일, 시험, 여행 등 중요한 날까지 D-Day 확인.',
      keywords: ['D-Day 계산기', '디데이 계산', '남은 일수', '기념일 계산', '100일 계산'],
      category: '생활/사회',
    },
    
    // === 업무/생산성 분야 ===
    {
      id: 'character-counter',
      path: '/tools/character-counter',
      title: '자기소개서 글자수 세기 - 공백 포함/제외 실시간 계산',
      description: '텍스트의 글자 수, 단어 수, 바이트 수를 실시간으로 계산합니다. 자기소개서, 이력서 작성 시 유용.',
      keywords: ['글자수 세기', '자기소개서 글자수', '문자 수 계산', '바이트 계산', '공백 포함'],
      category: '업무/생산성',
    },
    {
      id: 'percent-calculator',
      path: '/tools/percent-calculator',
      title: '퍼센트 계산기 - 비율, 할인율, 증감률 계산',
      description: '퍼센트(%) 계산을 쉽게! A의 B%는? 증감률은? 할인가는? 다양한 퍼센트 계산을 지원합니다.',
      keywords: ['퍼센트 계산기', '비율 계산', '할인율 계산', '증감률 계산', '% 계산'],
      category: '업무/생산성',
    },
    {
      id: 'unit-converter',
      path: '/tools/unit-converter',
      title: '단위 변환기 - 길이/면적/무게/온도 변환 (평수↔제곱미터)',
      description: '평수를 제곱미터로, 인치를 센티미터로! 길이, 면적, 무게, 온도, 데이터 용량 단위를 쉽게 변환.',
      keywords: ['단위 변환기', '평수 계산', '제곱미터', '인치 센티미터', '단위 환산'],
      category: '업무/생산성',
    },
    
    // === 개발/IT 분야 ===
    {
      id: 'json-formatter',
      path: '/tools/json-formatter',
      title: 'JSON Formatter & Validator - JSON 정렬/검증 도구',
      description: 'JSON 코드를 예쁘게 정렬(Pretty Print)하고 문법 오류를 검사합니다. 개발자 필수 도구.',
      keywords: ['JSON 포맷터', 'JSON 정렬', 'JSON 검증', 'JSON validator', 'Pretty Print'],
      category: '개발/IT',
    },
    {
      id: 'base64',
      path: '/tools/base64',
      title: 'Base64 인코더/디코더 - 텍스트 Base64 변환',
      description: '텍스트를 Base64로 인코딩하거나 Base64를 원본 텍스트로 디코딩합니다. UTF-8 한글 지원.',
      keywords: ['Base64 인코딩', 'Base64 디코딩', 'Base64 변환', '인코더', '디코더'],
      category: '개발/IT',
    },
    {
      id: 'url-encoder',
      path: '/tools/url-encoder',
      title: 'URL 인코더/디코더 - 한글 URL 퍼센트 인코딩',
      description: 'URL에 포함된 한글, 특수문자를 안전하게 인코딩하거나 디코딩합니다. encodeURI/encodeURIComponent.',
      keywords: ['URL 인코딩', 'URL 디코딩', '퍼센트 인코딩', 'encodeURI', 'URL 변환'],
      category: '개발/IT',
    },
    {
      id: 'lorem-ipsum',
      path: '/tools/lorem-ipsum',
      title: 'Lorem Ipsum 생성기 - 더미 텍스트 생성',
      description: '웹사이트, 앱, 문서 디자인에 사용할 더미 텍스트(Lorem Ipsum)를 문단/문장/단어 단위로 생성.',
      keywords: ['Lorem Ipsum', '더미 텍스트', '로렘 입숨', '테스트 텍스트', 'placeholder text'],
      category: '개발/IT',
    },

    // === 게임/재미 분야 ===
    {
      id: 'spin-wheel',
      path: '/tools/spin-wheel',
      title: '복불복 룰렛 돌리기 - 랜덤 선택 게임',
      description: '원판에 항목을 입력하고 회전시켜 랜덤하게 하나를 선정하는 인터랙티브 게임입니다.',
      keywords: ['복불복', '룰렛', '랜덤 선택', '뽑기', '돌림판', 'spin wheel'],
      category: '게임/재미',
    },
    {
      id: 'food-slot-machine',
      path: '/tools/food-slot-machine',
      title: '음식 메뉴 슬롯머신 - 오늘 뭐먹지?',
      description: '슬롯 레버를 당기면 한식, 중식, 일식 아이콘이 돌아가며 메뉴가 결정됩니다.',
      keywords: ['오늘 뭐먹지', '메뉴 추천', '점심 메뉴', '음식 룰렛', '슬롯머신'],
      category: '게임/재미',
    },
    {
      id: 'scratch-card',
      path: '/tools/scratch-card',
      title: '벌칙 복권 긁기 - 스크래치 카드 게임',
      description: '마우스로 화면을 문지르면 숨겨진 벌칙이나 당첨 결과가 나타나는 도구입니다.',
      keywords: ['복권 긁기', '스크래치', '벌칙 게임', '술자리 게임', '파티 게임'],
      category: '게임/재미',
    },
    {
      id: 'team-generator',
      path: '/tools/team-generator',
      title: '랜덤 조/팀 나누기 - 공정한 팀 배정',
      description: '참여자 명단을 넣고 팀 수를 정하면 공평하게 그룹을 생성해 결과를 보여줍니다.',
      keywords: ['팀 나누기', '조 편성', '랜덤 팀', '그룹 나누기', '팀빌딩'],
      category: '게임/재미',
    },
    {
      id: 'magic-conch',
      path: '/tools/magic-conch',
      title: '마법의 소라고동 결정기 - 고민 해결사',
      description: '고민을 입력하면 소라고동이 "지금 해", "하지 마" 등 랜덤한 답변을 내려줍니다.',
      keywords: ['소라고동', '결정 장애', '예스 노', '랜덤 답변', '고민 해결'],
      category: '게임/재미',
    },
    {
      id: 'fortune-cookie',
      path: '/tools/fortune-cookie',
      title: '오늘의 포춘 쿠키 - 매일 운세 확인',
      description: '매일 쿠키를 클릭해 깨뜨리면 오늘의 격언이나 운세를 확인하는 감성 도구입니다.',
      keywords: ['포춘쿠키', '오늘의 운세', '격언', '행운', '운세 확인'],
      category: '게임/재미',
    },
    {
      id: 'reaction-test',
      path: '/tools/reaction-test',
      title: '반응 속도 테스트 - 인간 벤치마크',
      description: '화면 색상이 변할 때 클릭하여 반응 속도를 측정하고 등급을 확인합니다.',
      keywords: ['반응 속도', '반응 테스트', '클릭 속도', '인간 벤치마크', 'reaction test'],
      category: '게임/재미',
    },

    // === 유틸리티 분야 ===
    {
      id: 'word-frequency',
      path: '/tools/word-frequency',
      title: '단어 빈도수 분석기 - 텍스트 분석 도구',
      description: '긴 글을 입력하면 어떤 단어가 가장 많이 쓰였는지 순위별로 보여줍니다.',
      keywords: ['단어 빈도', '텍스트 분석', '단어 카운트', '글 분석', 'word frequency'],
      category: '유틸리티',
    },
    {
      id: 'browser-info',
      path: '/tools/browser-info',
      title: '웹 브라우저 정보 확인 - My User Agent',
      description: '현재 내가 사용하는 브라우저 버전, 운영체제, IP 주소 등을 한눈에 보여줍니다.',
      keywords: ['브라우저 정보', 'user agent', '내 IP', '시스템 정보', 'browser info'],
      category: '유틸리티',
    },
    {
      id: 'reserve-calculator',
      path: '/tools/reserve-calculator',
      title: '예비군/민방위 연차 계산기 - 훈련 유형 확인',
      description: '전역 연도를 입력하면 현재 몇 년차 예비군인지, 어떤 교육을 받아야 하는지 알려줍니다.',
      keywords: ['예비군 계산기', '민방위 연차', '예비군 훈련', '동원훈련', '기본훈련'],
      category: '유틸리티',
    },
    {
      id: 'sleep-calculator',
      path: '/tools/sleep-calculator',
      title: '수면 사이클 계산기 - 최적 기상 시간',
      description: '가장 개운하게 일어날 수 있는 기상 시간 혹은 지금 자면 언제 일어나야 하는지를 제안합니다.',
      keywords: ['수면 계산기', '수면 사이클', '기상 시간', 'REM 수면', '최적 수면'],
      category: '유틸리티',
    },
    
    // === 새로 추가된 도구들 ===
    {
      id: 'qr-generator',
      path: '/tools/qr-generator',
      title: 'QR 코드 생성기 - 텍스트, URL QR 코드 만들기',
      description: '텍스트, URL, 연락처 등을 QR 코드로 변환합니다. PNG, SVG 다운로드 및 색상 커스터마이징 지원.',
      keywords: ['QR 코드', 'QR 생성기', 'QR코드 만들기', 'URL QR', 'QR code generator'],
      category: '개발/IT',
    },
    {
      id: 'case-converter',
      path: '/tools/case-converter',
      title: '텍스트 대소문자 변환기 - UPPER/lower/camelCase',
      description: '텍스트를 대문자, 소문자, 첫글자 대문자, camelCase, PascalCase, snake_case 등으로 변환합니다.',
      keywords: ['대소문자 변환', 'case converter', 'camelCase', 'snake_case', '대문자 변환'],
      category: '업무/생산성',
    },
    {
      id: 'coin-flip',
      path: '/tools/coin-flip',
      title: '동전 던지기 - 앞면 뒷면 랜덤 결정',
      description: '3D 애니메이션과 함께 동전을 던져 앞면/뒷면을 결정합니다. 결과 통계도 제공.',
      keywords: ['동전 던지기', 'coin flip', '앞면 뒷면', '랜덤 결정', '동전 게임'],
      category: '게임/재미',
    },
    {
      id: 'dice-roller',
      path: '/tools/dice-roller',
      title: '디지털 주사위 굴리기 - D6, D20 등 다양한 주사위',
      description: '1~6개의 주사위를 굴립니다. D4, D6, D8, D10, D12, D20, D100 등 TRPG 주사위 지원.',
      keywords: ['주사위', 'dice roller', 'D20', 'TRPG', '주사위 굴리기'],
      category: '게임/재미',
    },
    {
      id: 'mandalart',
      path: '/tools/mandalart',
      title: '만다라트 계획표 - 오타니식 9x9 목표 설정',
      description: '핵심 목표를 중심으로 8가지 세부 목표를 설정하는 만다라트 계획표입니다. 오타니 쇼헤이 방식.',
      keywords: ['만다라트', 'mandal-art', '목표 설정', '오타니 계획표', '9x9 계획'],
      category: '업무/생산성',
    },
    {
      id: 'korean-romanizer',
      path: '/tools/korean-romanizer',
      title: '한글 로마자 변환기 - 영문 이름 표기',
      description: '한글 이름을 국제 표준 로마자 표기법으로 변환합니다. 여권용 영문 이름 확인에 유용.',
      keywords: ['로마자 변환', '영문 이름', 'romanizer', '여권 이름', '한글 로마자'],
      category: '유틸리티',
    },
    {
      id: 'number-base-converter',
      path: '/tools/number-base-converter',
      title: '진수 변환기 - 2진수/8진수/10진수/16진수',
      description: '이진수, 팔진수, 십진수, 16진수 간 변환합니다. 비트 연산 기능도 제공.',
      keywords: ['진수 변환', '2진수', '16진수', 'binary converter', 'hex converter'],
      category: '개발/IT',
    },
    {
      id: 'list-shuffler',
      path: '/tools/list-shuffler',
      title: '리스트 셔플러 - 목록 순서 무작위 섞기',
      description: '여러 줄의 항목을 무작위로 섞습니다. 발표 순서, 추첨, 랜덤 정렬에 활용하세요.',
      keywords: ['리스트 셔플', '순서 섞기', '랜덤 정렬', 'shuffle', '무작위 순서'],
      category: '게임/재미',
    },
    {
      id: 'timer',
      path: '/tools/timer',
      title: '웹 타이머 & 스톱워치 - 뽀모도로 타이머',
      description: '타이머, 스톱워치, 뽀모도로 타이머를 제공합니다. 집중 시간 관리에 최적화.',
      keywords: ['타이머', '스톱워치', '뽀모도로', 'pomodoro', '시간 관리'],
      category: '업무/생산성',
    },
    {
      id: 'color-converter',
      path: '/tools/color-converter',
      title: '색상 코드 변환기 - HEX/RGB/HSL 변환',
      description: 'HEX, RGB, HSL 색상 코드를 상호 변환합니다. 보색, 유사색, 삼원색 하모니도 제공.',
      keywords: ['색상 변환', 'HEX to RGB', 'color converter', 'HSL', '컬러 코드'],
      category: '개발/IT',
    },
    {
      id: 'sticky-note',
      path: '/tools/sticky-note',
      title: '온라인 메모장 - 임시 텍스트 저장',
      description: '브라우저에서 빠르게 메모를 작성하고 저장합니다. 자동 저장, 다크모드 지원.',
      keywords: ['메모장', '온라인 메모', '임시 메모', 'sticky note', '웹 메모장'],
      category: '업무/생산성',
    },
    {
      id: 'webp-converter',
      path: '/tools/webp-converter',
      title: '이미지 WebP 변환기 - PNG/JPG to WebP',
      description: 'PNG, JPG 이미지를 WebP 포맷으로 변환하여 파일 크기를 줄입니다. 품질 조절 가능.',
      keywords: ['WebP 변환', '이미지 변환', 'PNG to WebP', '이미지 압축', 'webp converter'],
      category: '개발/IT',
    },
    {
      id: 'ip-port-checker',
      path: '/tools/ip-port-checker',
      title: '공인 IP 확인 & 포트 체커 - 내 IP 주소',
      description: '현재 공인 IP 주소와 위치 정보를 확인합니다. 포트 열림 여부 테스트 기능 제공.',
      keywords: ['내 IP', '공인 IP', '포트 체커', 'IP 확인', 'port checker'],
      category: '개발/IT',
    },

    // === 쇼핑/실생활 분야 ===
    {
      id: 'unit-price-calculator',
      path: '/tools/unit-price-calculator',
      title: '마트 단위당 가격 비교기 - 가성비 계산 (100g/100ml당)',
      description: '용량과 가격이 다른 상품의 100ml/100g당 가격을 계산하여 어떤 것이 더 저렴한지 비교합니다. 마트 장보기 필수 도구.',
      keywords: ['단위당 가격', '가성비 계산기', '마트 가격 비교', '100ml당 가격', '100g당 가격', '장보기 도구'],
      category: '쇼핑/실생활',
    },
    {
      id: 'discount-calculator',
      path: '/tools/discount-calculator',
      title: '할인율 계산기 - 세일 가격, 최종 결제 금액 계산',
      description: '정가와 할인율을 입력하면 할인 금액과 최종 결제 금액을 즉시 계산합니다. 쇼핑 세일 시즌 필수 도구.',
      keywords: ['할인율 계산기', '세일 가격', '할인 금액', '퍼센트 할인', '최종 가격 계산'],
      category: '쇼핑/실생활',
    },
    {
      id: 'size-converter',
      path: '/tools/size-converter',
      title: '해외 사이즈 변환기 - US/EU/UK 신발 의류 사이즈',
      description: '미국(US), 유럽(EU), 영국(UK) 신발 및 의류 사이즈를 한국 사이즈로 변환합니다. 해외직구 필수 도구.',
      keywords: ['사이즈 변환', '해외 사이즈', 'US 사이즈', 'EU 사이즈', '신발 사이즈', '의류 사이즈', '해외직구'],
      category: '쇼핑/실생활',
    },
    {
      id: 'water-intake-calculator',
      path: '/tools/water-intake-calculator',
      title: '하루 권장 음수량 계산기 - 물 섭취량 계산',
      description: '체중과 활동량을 바탕으로 하루에 마셔야 할 적정 물 섭취량을 컵 단위로 계산합니다. 건강 관리 필수 도구.',
      keywords: ['물 섭취량', '권장 음수량', '하루 물', '수분 섭취', '물 마시기', '건강 관리'],
      category: '건강/라이프스타일',
    },

    // === 유틸리티/개발 추가 분야 ===
    {
      id: 'html-stripper',
      path: '/tools/html-stripper',
      title: 'HTML 태그 제거기 - 순수 텍스트 추출 도구',
      description: 'HTML 코드에서 모든 태그를 제거하고 순수 텍스트만 추출합니다. 웹 콘텐츠 복사, 데이터 정리 시 유용.',
      keywords: ['HTML 태그 제거', '태그 삭제', '텍스트 추출', 'strip tags', 'HTML to text'],
      category: '개발/IT',
    },
    {
      id: 'morse-code',
      path: '/tools/morse-code',
      title: '모스 부호 변환기 - 텍스트 ↔ 모스 코드',
      description: '텍스트를 모스 부호로, 모스 부호를 텍스트로 양방향 변환합니다. 소리 재생 기능 지원.',
      keywords: ['모스 부호', '모스 코드', 'Morse code', '부호 변환', 'SOS'],
      category: '유틸리티',
    },

    // === 음악/창작 분야 ===
    {
      id: 'metronome',
      path: '/tools/metronome',
      title: '온라인 메트로놈 - BPM 박자기, TAP 템포',
      description: '웹 기반 메트로놈. BPM 조절, TAP 템포 감지, 다양한 박자 설정으로 음악 연습을 도와드립니다.',
      keywords: ['메트로놈', 'BPM', '박자기', 'TAP 템포', '음악 연습', '온라인 메트로놈'],
      category: '음악/창작',
    },
    {
      id: 'chord-transposer',
      path: '/tools/chord-transposer',
      title: '코드 조바꿈 도구 - 악보 키 변경, 카포 계산',
      description: '기타/피아노 코드를 원하는 키로 조바꿈합니다. 카포 위치 추천, 일반 코드 진행 프리셋 제공.',
      keywords: ['조바꿈', '코드 변환', '키 변경', '카포 계산', '기타 코드', '악보 변환'],
      category: '음악/창작',
    },

    // === 디자인 분야 ===
    {
      id: 'palette-generator',
      path: '/tools/palette-generator',
      title: '랜덤 색상 조합 생성기 - 컬러 팔레트 메이커',
      description: '어울리는 5가지 색상 조합을 랜덤으로 생성합니다. 유사색, 보색, 파스텔 등 다양한 팔레트 유형 지원.',
      keywords: ['색상 조합', '컬러 팔레트', 'color palette', '색상 생성기', '디자인 색상', 'HEX 코드'],
      category: '디자인',
    },
    {
      id: 'gradient-generator',
      path: '/tools/gradient-generator',
      title: 'CSS 그래디언트 생성기 - 선형/원형 그라데이션 메이커',
      description: 'CSS linear-gradient, radial-gradient 코드를 시각적으로 생성합니다. 멀티 컬러 스톱, 각도 조절, 프리셋 지원.',
      keywords: ['CSS 그래디언트', 'gradient generator', 'linear-gradient', 'radial-gradient', '그라데이션', '배경색'],
      category: '디자인',
    },
    {
      id: 'box-shadow-generator',
      path: '/tools/box-shadow-generator',
      title: '박스 쉐도우 생성기 - CSS 그림자 디자인 툴',
      description: 'CSS box-shadow를 시각적으로 디자인합니다. 다중 레이어 그림자, inset, 색상/블러 조절 지원.',
      keywords: ['box-shadow', 'CSS 그림자', '박스 쉐도우', 'shadow generator', '그림자 효과', 'CSS 디자인'],
      category: '디자인',
    },
    {
      id: 'glassmorphism-generator',
      path: '/tools/glassmorphism-generator',
      title: '글래스모피즘 UI 생성기 - 반투명 유리 효과',
      description: '모던한 글래스모피즘(유리 효과) CSS를 생성합니다. backdrop-filter, 투명도, 블러 조절 지원.',
      keywords: ['glassmorphism', '글래스모피즘', '유리 효과', 'backdrop-filter', 'UI 디자인', 'blur 효과'],
      category: '디자인',
    },
    {
      id: 'neumorphism-generator',
      path: '/tools/neumorphism-generator',
      title: '뉴모피즘 디자인 생성기 - Soft UI 버튼/카드',
      description: '부드러운 3D 느낌의 뉴모피즘 CSS를 생성합니다. flat, concave, convex, pressed 스타일 지원.',
      keywords: ['neumorphism', '뉴모피즘', 'soft UI', '소프트 UI', '3D 버튼', 'CSS 디자인'],
      category: '디자인',
    },
    {
      id: 'css-grid-generator',
      path: '/tools/css-grid-generator',
      title: 'CSS 그리드 레이아웃 생성기 - 드래그로 영역 설정',
      description: 'CSS Grid 레이아웃을 시각적으로 설계합니다. 드래그로 영역 병합, grid-template-areas 코드 생성.',
      keywords: ['CSS Grid', '그리드 레이아웃', 'grid generator', 'grid-template-areas', '웹 레이아웃', 'CSS 레이아웃'],
      category: '디자인',
    },

    // === 건강/생활 추가 분야 ===
    {
      id: 'caffeine-calculator',
      path: '/tools/caffeine-calculator',
      title: '일일 카페인 섭취량 계산기 - 커피 권장량 체크',
      description: '커피, 에너지 드링크 등 음료별 카페인 함량을 계산하여 하루 권장량(400mg) 대비 섭취 수준을 확인합니다.',
      keywords: ['카페인 계산기', '커피 카페인', '일일 카페인', '카페인 권장량', '에너지 드링크 카페인'],
      category: '건강/라이프스타일',
    },
    {
      id: 'lunar-calendar',
      path: '/tools/lunar-calendar',
      title: '음력 양력 변환기 & 손 없는 날 - 이사 길일',
      description: '양력을 음력으로 변환하고, 이사나 개업에 좋은 손 없는 날을 달력에서 확인합니다.',
      keywords: ['음력 양력 변환', '손 없는 날', '이사 날짜', '음력 달력', '개업 길일', '손없는날'],
      category: '생활/사회',
    },

    // === 개발/IT 추가 분야 ===
    {
      id: 'diff-checker',
      path: '/tools/diff-checker',
      title: '텍스트 차이 비교기 (Diff Checker) - 코드 비교 도구',
      description: '두 텍스트의 차이점을 줄 단위로 비교하여 변경된 부분을 하이라이트로 표시합니다. 코드 리뷰, 문서 수정에 유용.',
      keywords: ['Diff Checker', '텍스트 비교', '코드 비교', '차이점 비교', 'diff tool', '문서 비교'],
      category: '개발/IT',
    },
    {
      id: 'favicon-generator',
      path: '/tools/favicon-generator',
      title: '파비콘 생성기 - 웹사이트 아이콘 만들기 (모든 크기)',
      description: '이미지를 업로드하면 웹사이트에 필요한 모든 크기의 파비콘(16x16~512x512)을 자동 생성합니다.',
      keywords: ['파비콘 생성기', 'favicon', '웹사이트 아이콘', 'apple touch icon', '파비콘 만들기'],
      category: '개발/IT',
    },
    {
      id: 'exif-remover',
      path: '/tools/exif-remover',
      title: '이미지 EXIF 메타데이터 삭제기 - 위치 정보 제거',
      description: '사진 파일의 GPS 위치, 카메라 정보, 촬영 날짜 등 EXIF 메타데이터를 안전하게 삭제합니다.',
      keywords: ['EXIF 삭제', '메타데이터 제거', '위치 정보 삭제', '사진 개인정보', 'EXIF remover'],
      category: '개발/IT',
    },
    {
      id: 'exif-viewer',
      path: '/tools/exif-viewer',
      title: '이미지 EXIF 메타데이터 확인기 - 사진 정보 조회',
      description: '사진 파일에 포함된 GPS 위치, 카메라 정보, 촬영 설정 등 EXIF 메타데이터를 조회합니다.',
      keywords: ['EXIF 확인', '메타데이터 조회', '사진 정보', 'EXIF viewer', '촬영 정보'],
      category: '개발/IT',
    },

    // === 디자인 도구 추가 ===
    {
      id: 'placeholder-image',
      path: '/tools/placeholder-image',
      title: '플레이스홀더 이미지 생성기 - 임시 이미지 URL 만들기',
      description: '특정 크기와 색상의 플레이스홀더 이미지를 URL 형태로 생성합니다. 웹 개발 초기 단계 레이아웃 테스트에 필수.',
      keywords: ['플레이스홀더 이미지', 'placeholder image', '임시 이미지', '더미 이미지', '개발용 이미지'],
      category: '디자인',
    },
    {
      id: 'svg-blob-generator',
      path: '/tools/svg-blob-generator',
      title: 'SVG 블롭 생성기 - 유기적인 곡선 도형 만들기',
      description: '웹 디자인 배경에 사용할 부드럽고 유기적인 곡선 형태의 SVG 블롭을 무작위로 생성합니다.',
      keywords: ['SVG 블롭', 'blob generator', '유기적 도형', '웹 디자인', 'SVG 배경'],
      category: '디자인',
    },
    {
      id: 'social-media-size-guide',
      path: '/tools/social-media-size-guide',
      title: '소셜 미디어 이미지 사이즈 가이드 (2026) - 인스타 유튜브 틱톡',
      description: '인스타그램, 유튜브, 틱톡, 페이스북 등 주요 소셜 미디어 플랫폼별 최신 권장 이미지 사이즈를 안내합니다.',
      keywords: ['인스타 사이즈', '소셜 미디어 사이즈', '유튜브 썸네일', '틱톡 사이즈', '이미지 크기'],
      category: '디자인',
    },
    {
      id: 'css-filter-lab',
      path: '/tools/css-filter-lab',
      title: 'CSS 필터 실험실 - 이미지 필터 효과 (Blur, Sepia 등)',
      description: '이미지에 Blur, Brightness, Contrast, Sepia 등 CSS 필터를 적용해보고 코드를 복사합니다.',
      keywords: ['CSS filter', '이미지 필터', 'blur 효과', 'sepia 필터', 'CSS 이미지 효과'],
      category: '디자인',
    },
    {
      id: 'css-pattern-generator',
      path: '/tools/css-pattern-generator',
      title: 'CSS 배경 패턴 생성기 - 도트, 체크, 스트라이프',
      description: '도트, 체크, 스트라이프 등 반복되는 배경 패턴을 이미지 없이 CSS 코드로만 생성합니다. 웹 성능 최적화에 최적.',
      keywords: ['CSS 패턴', '배경 패턴', 'CSS background', '도트 패턴', '체크 패턴', '웹 성능'],
      category: '디자인',
    },

    // === UI/UX 및 편의 도구 ===
    {
      id: 'logo-safe-area',
      path: '/tools/logo-safe-area',
      title: '로고 안전 영역 생성기 - 브랜드 가이드라인 그리드',
      description: '로고 파일에 상하좌우 여백과 그리드를 그려 브랜드 가이드라인 준수를 돕습니다. 브랜딩 디자이너 필수 도구.',
      keywords: ['로고 안전 영역', 'Safe Area', '브랜드 가이드라인', '로고 그리드', '로고 여백', '브랜딩'],
      category: '디자인',
    },
    {
      id: 'favicon-preview',
      path: '/tools/favicon-preview',
      title: '파비콘 미리보기 - 브라우저 탭 & 모바일 시뮬레이션',
      description: '파비콘이 브라우저 탭, 즐겨찾기 바, 모바일 홈 화면에서 어떻게 보이는지 미리 확인합니다.',
      keywords: ['파비콘 미리보기', 'favicon preview', '브라우저 탭 아이콘', '웹사이트 아이콘', '모바일 아이콘'],
      category: '개발/IT',
    },
    {
      id: 'button-generator',
      path: '/tools/button-generator',
      title: '버튼 디자인 팩토리 - Tailwind CSS 버튼 생성기',
      description: '둥글기, 그림자, 호버 효과가 적용된 세련된 버튼을 만들고 Tailwind CSS 또는 CSS 코드로 내보냅니다.',
      keywords: ['버튼 생성기', 'Button Generator', 'Tailwind 버튼', 'CSS 버튼', '버튼 디자인'],
      category: '디자인',
    },
    {
      id: 'color-blindness-simulator',
      path: '/tools/color-blindness-simulator',
      title: '색약 시뮬레이터 - 웹 접근성 색각 이상 테스트',
      description: '디자인이 색약(적록색맹, 청색맹 등) 사용자에게 어떻게 보이는지 필터를 씌워 확인합니다. 웹 접근성 필수 도구.',
      keywords: ['색약 시뮬레이터', 'Color Blindness', '색각 이상', '웹 접근성', '적록색맹', 'WCAG'],
      category: '디자인',
    },
    {
      id: 'screen-resolution',
      path: '/tools/screen-resolution',
      title: '화면 해상도 확인기 - 내 모니터 해상도 & PPI 확인',
      description: '현재 기기의 논리적/물리적 해상도, 픽셀 밀도(DPR), PPI를 즉시 확인합니다.',
      keywords: ['해상도 확인', '내 해상도', '모니터 해상도', 'PPI 확인', '화면 크기', 'DPR'],
      category: '유틸리티',
    },
  ],
};

// 도구 정보 타입
export interface ToolInfo {
  id: string;
  path: string;
  title: string;
  description: string;
  keywords: string[];
  category: string;
}
